/* Generated By:JavaCC: Do not edit this line. BifParserConstants.java */
package org.latlab.io.bif;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BifParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEWLINE = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int ALPHA = 3;
  /** RegularExpression Id. */
  int UNICODE_CHAR = 4;
  /** RegularExpression Id. */
  int ALPHA_DASH = 5;
  /** RegularExpression Id. */
  int ALPHA_DASH_SPACE = 6;
  /** RegularExpression Id. */
  int UTF8_INDICATOR = 7;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int NETWORK = 11;
  /** RegularExpression Id. */
  int VARIABLE = 12;
  /** RegularExpression Id. */
  int EDGE = 13;
  /** RegularExpression Id. */
  int HEAD = 14;
  /** RegularExpression Id. */
  int TAIL = 15;
  /** RegularExpression Id. */
  int PROBABILITY = 16;
  /** RegularExpression Id. */
  int TYPE = 17;
  /** RegularExpression Id. */
  int DISCRETE = 18;
  /** RegularExpression Id. */
  int DEFAULT_VALUE = 19;
  /** RegularExpression Id. */
  int TABLE = 20;
  /** RegularExpression Id. */
  int PROPERTY = 21;
  /** RegularExpression Id. */
  int EXPONENT = 22;
  /** RegularExpression Id. */
  int NON_NEGATIVE_INTEGER = 23;
  /** RegularExpression Id. */
  int NON_NEGATIVE_FLOAT = 24;
  /** RegularExpression Id. */
  int IDENTIFIER = 25;
  /** RegularExpression Id. */
  int PROPERTY_DOUBLE_QUOTE = 26;
  /** RegularExpression Id. */
  int POSITION = 27;
  /** RegularExpression Id. */
  int ROTATION = 28;
  /** RegularExpression Id. */
  int FRAME = 29;
  /** RegularExpression Id. */
  int LABEL = 30;
  /** RegularExpression Id. */
  int FORECOLOR = 31;
  /** RegularExpression Id. */
  int BACKCOLOR = 32;
  /** RegularExpression Id. */
  int LINECOLOR = 33;
  /** RegularExpression Id. */
  int FONT = 34;
  /** RegularExpression Id. */
  int FONTSIZE = 35;
  /** RegularExpression Id. */
  int CONNECTION_CONSTRAINT = 36;
  /** RegularExpression Id. */
  int NONE = 37;
  /** RegularExpression Id. */
  int OVAL = 38;
  /** RegularExpression Id. */
  int RECTANGLE = 39;
  /** RegularExpression Id. */
  int PROPERTY_EQUAL = 40;
  /** RegularExpression Id. */
  int PROPERTY_LPARENTHESE = 41;
  /** RegularExpression Id. */
  int PROPERTY_RPARENTHESE = 42;
  /** RegularExpression Id. */
  int PROPERTY_COMMA = 43;
  /** RegularExpression Id. */
  int PROPERTY_END_CHAR = 44;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 45;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int PROPERTY_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NEWLINE>",
    "<DIGIT>",
    "<ALPHA>",
    "<UNICODE_CHAR>",
    "<ALPHA_DASH>",
    "<ALPHA_DASH_SPACE>",
    "\"\\ufeff\"",
    "\" \"",
    "\"\\t\"",
    "<SINGLE_LINE_COMMENT>",
    "\"network\"",
    "\"variable\"",
    "\"edge\"",
    "\"head\"",
    "\"tail\"",
    "\"probability\"",
    "\"type\"",
    "\"discrete\"",
    "\"default\"",
    "\"table\"",
    "\"property\"",
    "<EXPONENT>",
    "<NON_NEGATIVE_INTEGER>",
    "<NON_NEGATIVE_FLOAT>",
    "<IDENTIFIER>",
    "\"\\\"\"",
    "\"position\"",
    "\"rotation\"",
    "\"frame\"",
    "\"label\"",
    "\"foreColor\"",
    "\"backColor\"",
    "\"lineColor\"",
    "\"font\"",
    "\"fontSize\"",
    "\"connectionConstraint\"",
    "\"none\"",
    "\"oval\"",
    "\"rectangle\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "<SINGLE_QUOTED_STRING>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\"=\"",
    "\";\"",
    "\")\"",
    "\",\"",
    "\"|\"",
    "\"[\"",
    "\"]\"",
  };

}
