/* Generated By:JavaCC: Do not edit this line. ArffParserConstants.java */
package hk.ust.cse.lantern.data.io.arff;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ArffParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEWLINE = 5;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int ALPHA = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int UNICODE_CHAR = 9;
  /** RegularExpression Id. */
  int SPACE = 10;
  /** RegularExpression Id. */
  int RELATION = 11;
  /** RegularExpression Id. */
  int ATTRIBUTE = 12;
  /** RegularExpression Id. */
  int DATA = 13;
  /** RegularExpression Id. */
  int REAL = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int EXPONENT = 16;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 17;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 18;
  /** RegularExpression Id. */
  int DQUOTED_STRING_LITERAL = 19;
  /** RegularExpression Id. */
  int SQUOTED_STRING_LITERAL = 20;
  /** RegularExpression Id. */
  int STRING_LITERAL = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NEWLINE>",
    "<SINGLE_LINE_COMMENT>",
    "<ALPHA>",
    "<DIGIT>",
    "<UNICODE_CHAR>",
    "<SPACE>",
    "\"@relation\"",
    "\"@attribute\"",
    "\"@data\"",
    "\"real\"",
    "\"integer\"",
    "<EXPONENT>",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DQUOTED_STRING_LITERAL>",
    "<SQUOTED_STRING_LITERAL>",
    "<STRING_LITERAL>",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"?\"",
  };

}
